StoreApp/Controllers/OrderController.cs
using Entities.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IServiceManager _manager;
        private readonly Cart _cart;

        public OrderController(IServiceManager manager, Cart cart)
        {
            _manager = manager;
            _cart = cart;
        }
        [Authorize]
        public ViewResult Checkout() => View(new Order());

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Checkout([FromForm] Order order)
        {
            if(_cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("","Sorry, your cart is empty.");
            }

            if(ModelState.IsValid)
            {
                order.Lines = _cart.Lines.ToArray();
                _manager.OrderService.SaveOrder(order);
                _cart.Clear();
                return RedirectToPage("/Complete", new {OrderId = order.OrderId});
            }
            else
            {
                return View();
            }
        }
    }
}

StoreApp/Pages/Cart.cshtml.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.Contracts;
using StoreApp.Infrastructure.Extensions;

namespace StoreApp.Pages
{
    public class CartModel : PageModel
    {
        private readonly IServiceManager _manager;
        public Cart Cart { get; set; } // IoC
        public string ReturnUrl { get; set; } = "/";

        public CartModel(IServiceManager manager, Cart cartService)
        {
            _manager = manager;
            Cart = cartService;
        }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            // Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        }

        public IActionResult OnPost(int productId, string returnUrl)
        {
            Product? product = _manager.ProductService.GetOneProduct(productId, false);

            if (product is not null)
            {
                // Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
                Cart.AddItem(product, 1);
                // HttpContext.Session.SetJson<Cart>("cart", Cart);
            }
            return RedirectToPage(new { returnUrl = returnUrl}); //returnUrl
        }

        public IActionResult OnPostRemove(int id, string returnUrl)
        {
            // Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
            Cart.RemoveLine(Cart.Lines.First(cl => cl.Product.ProductId.Equals(id)).Product);
            // HttpContext.Session.SetJson<Cart>("cart", Cart);
            return Page();
        }
    }
}

StoreApp/Pages/Demo.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StoreApp.Pages
{
    public class DemoModel : PageModel
    {
        public String? FullName => HttpContext?.Session?.GetString("name") ?? "";

        public void OnGet()
        {

        }

        public void OnPost([FromForm] string name)
        {
            // FullName = name;
            HttpContext.Session.SetString("name", name);
        }
    }
}

StoreApp/Pages/Cart.cshtml
@page "/cart"
@model CartModel

<div>
    <div class="text-center display-6">
        Cart
    </div>
    <table>
        <thead>
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var line in Model.Cart?.Lines ?? Enumerable.Empty<CartLine>())
            {
                <tr>
                    <td>@line.Product.ProductName</td>
                    <td>@line.Quantity</td>
                    <td>@line.Product.Price.ToString("c")</td>
                    <td>@((line.Product.Price*line.Quantity).ToString("c2"))</td>
                    <td>
                        <form method="post" asp-page-handler="Remove">
                            <input type="hidden" name="id" value="@line.Product.ProductId" />
                            <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                            <button type="submit" class="btn btn-sm btn-danger">
                                <i class="fa fa-trash"></i>
                                Remove
                            </button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4" class="text-right">Total : </td>
                <td class="text-right text-danger">
                    @Model.Cart?.ComputeTotalValue().ToString("c2")
                </td>
            </tr>
        </tfoot>
    </table>
    <div class="text-center my-3">
        <div class="btn-group">
            <a class="btn btn-primary" href="@Model?.ReturnUrl">Continue Shopping</a>
            <a class="btn btn-primary mx-2" asp-action="Checkout" asp-controller="Order">Checkout</a>
        </div>
    </div>
</div>

StoreApp/Pages/Complete.cshtml
@page

<div class="text-center">
    <div class="display-6">Thanks</div>
    <p>Thanks for placing order #@OrderId</p>
    <p>We'll ship your goods as soon as possible.</p>
    <a class="btn btn-primary" asp-controller="Home" asp-action="Index">Return to Store</a>
</div>

@functions
{
    [BindProperty(SupportsGet = true)]
    public String? OrderId { get; set; }
}

StoreApp/Pages/Contact.cshtml
@page "/getintouch"

<div class="text-center border my-5 rounded">
    <div class="display-6 border-bottom">Contact</div>
    <div class="lead">
        <i class="fa fa-phone bg-secondary text-primary my-3 text-white p-3 rounded-5"></i>
        <p>
            ALO 120 BTK Akademi bilgi ve destek hattı
        </p>

        <i class="fa fa-address-book bg-secondary text-primary my-3 text-white p-3 rounded-5"></i>
        <p>
            Bilgi Teknolojileri ve İletişim Kurumu Eskişehir Yolu 10.Km
            No: 276 Posta Kodu: 06530 Çankaya/Ankara
        </p>

        <i class="fa-solid fa-envelope bg-secondary text-primary my-3 text-white p-3 rounded-5"></i>
        <p>
           destek@btkakademi.gov.tr 
        </p>
    </div>
</div>

StoreApp/Pages/Demo.cshtml
@page
@model StoreApp.Pages.DemoModel
@{
}

<div class="my-5 text-center">
    <div class="display-6">Hello @Model?.FullName</div>
    <p class="text-danger">@HttpContext.Session.GetString("name")</p>
    <form method="post" asp-page="/demo">
        <div class="form-group">
            <input class="form-control" name="name" placeholder="Enter your name" />
            <input type="submit" class="btn btn-primary my-3" />
        </div>
    </form>
</div>