StoreApp/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            TempData["info"] = $"Welcome back, {DateTime.Now.ToShortTimeString()}";
            return View();
        }
    }
}

StoreApp/Components/ShowCaseViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Components
{
    public class ShowCaseViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;

        public ShowCaseViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }

        public IViewComponentResult Invoke(string page = "default")
        {
            var products = _manager.ProductService.GetShowcaseProducts(false);
            return page.Equals("default")
                ? View(products)
                : View("List", products);
        }
    }
}

StoreApp/Controllers/CategoryController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contrats;

namespace StoreApp.Controllers
{
    public class CategoryController : Controller
    {
        private IRepositoryManager _manager;

        public CategoryController(IRepositoryManager manager)
        {
            _manager = manager;
        }
        public IActionResult Index ()
        {
            var model = _manager.Category.FindAll(false);
            return View(model);
        }
    }
}

StoreApp/Controllers/OrderController.cs
using Entities.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IServiceManager _manager;
        private readonly Cart _cart;

        public OrderController(IServiceManager manager, Cart cart)
        {
            _manager = manager;
            _cart = cart;
        }
        [Authorize]
        public ViewResult Checkout() => View(new Order());

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Checkout([FromForm] Order order)
        {
            if(_cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("","Sorry, your cart is empty.");
            }

            if(ModelState.IsValid)
            {
                order.Lines = _cart.Lines.ToArray();
                _manager.OrderService.SaveOrder(order);
                _cart.Clear();
                return RedirectToPage("/Complete", new {OrderId = order.OrderId});
            }
            else
            {
                return View();
            }
        }
    }
}

StoreApp/Controllers/ProductController.cs
using Entities.Models;
using Entities.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Repositories.Contrats;
using Services.Contracts;
using StoreApp.Models;

namespace StoreApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index(ProductRequestParameters p)
        {
            var products = _manager.ProductService.GetAllProductsWithDetails(p);
            var pagination = new Pagination()
            {
                CurrenPage = p.PageNumber,
                ItemsPerPage = p.PageSize,
                TotalItems = _manager.ProductService.GetAllProducts(false).Count()
            };
            return View(new ProductListViewModel()
            {
                Products = products,
                Pagination = pagination
            });
        }

        public IActionResult Get([FromRoute(Name = "id")] int id)
        {
            var model = _manager.ProductService.GetOneProduct(id, false);
            ViewData["Title"] = model?.ProductName;
            return View(model);
        }
    }
}

StoreApp/Areas/Admin/Views/Dashboard/Index.cshtml
<div class="my-5">
    <partial name="_Cards" />
</div>

@await Component.InvokeAsync("ShowCase", new {page="list"})

StoreApp/Areas/Admin/Views/Dashboard/_Cards.cshtml
<div class="row">
    <div class="col-md-3 p-2">
        <div class="card bg-primary text-white">
            <div class="card-body text-center">
                <h6 class="card-subtitle mb-2">Number of</h6>
                <h5 class="card-title">Products</h5>
                <h3 class="text-center display-3">
                    @await Component.InvokeAsync("ProductSummary")
                </h3>
                <a asp-controller="Product" asp-action="Index" class="card-link text-white">Products</a>
                <a asp-controller="Product" asp-action="Create" class="card-link text-white">New Product</a>
            </div>
        </div>
    </div>

    <div class="col-md-3 p-2">
        <div class="card bg-danger text-white">
            <div class="card-body text-center">
                <h6 class="card-subtitle mb-2">Number of</h6>
                <h5 class="card-title">Categories</h5>
                <h3 class="text-center display-3">
                    @await Component.InvokeAsync("CategorySummary")
                </h3>
                <a asp-controller="Category" asp-action="Index" class="card-link text-white">Categories</a>
                <a asp-controller="Category" asp-action="Create" class="card-link text-white">New Category</a>
            </div>
        </div>
    </div>

    <div class="col-md-3 p-2">
        <div class="card bg-info text-white">
            <div class="card-body text-center">
                <h6 class="card-subtitle mb-2">Number of</h6>
                <h5 class="card-title">Users</h5>
                <h3 class="text-center display-3">
                    @await Component.InvokeAsync("UserSummary")
                </h3>
                <a asp-controller="User" asp-action="Index" class="card-link text-white">Users</a>
                <a asp-controller="User" asp-action="Create" class="card-link text-white">New User</a>
            </div>
        </div>
    </div>

    <div class="col-md-3 p-2">
        <div class="card bg-warning text-white">
            <div class="card-body text-center">
                <h6 class="card-subtitle mb-2">Number of</h6>
                <h5 class="card-title">Orders in Progress</h5>
                <h3 class="text-center display-3">
                    @await Component.InvokeAsync("OrderInProgress")
                </h3>
                <a asp-controller="Order" asp-action="Index" class="card-link text-white">Orders</a>
            </div>
        </div>
    </div>

</div>